# Copyright 2020 Evan Miller
# Copyright 2020 Matt Borland
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

name: CI
on:
  push:
    branches:
      - master
      - develop
  pull_request:
  release:
    types: [published, created, edited]
jobs:
  standalone:
  runs-on: ubuntu-20.04
  strategy:
    fail-fast: false
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - uses: mstachniuk/ci-skip@v1
      with:
        commit-filter: '[skip ci];[ci skip];[CI SKIP];[SKIP CI];***CI SKIP***;***SKIP CI***;[windows];[Windows];[WINDOWS];[apple];[Apple];[APPLE]'
        commit-filter-separator: ';'
        fail-fast: true
    - name: Add repository
      continue-on-error: true
      id: addrepo
      run: sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
    - name: Retry Add Repo
      continue-on-error: true
      id: retry1
      if: steps.addrepo.outcome=='failure'
      run: sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
    - name: Retry Add Repo 2
      continue-on-error: true
      id: retry2
      if: steps.retry1.outcome=='failure'
      run: sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
    - name: Install packages
      run: sudo apt install g++-10
    - name: Checkout main boost
      run: git clone -b develop --depth 1 https://github.com/boostorg/boost.git ../boost-root
    - name: Update tools/boostdep
      run: git submodule update --init tools/boostdep
      working-directory: ../boost-root
    - name: Copy files
      run: cp -r $GITHUB_WORKSPACE/* libs/math
      working-directory: ../boost-root
    - name: Run CMake
      run: cmake -DBUILD_TESTING=1 .
      working-directory: ../boost-root/libs/math
    - name: Run Compile Tests
      run: make -j3
      working-directory: ../boost-root/libs/math
