# Copyright 2020 Evan Miller
# Copyright 2020 Matt Borland
# Copyright 2021 Christopher Kormanyos
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

name: e_float_boost_test
on:
  push:
    branches:
      - master
      - develop
  pull_request:
  release:
    types: [published, created, edited]
jobs:
  ubuntu-focal:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        compiler: [ g++ ]
        standard: [ gnu++11 ]
        suite: [ E_FLOAT_TYPE_EFX ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Set TOOLSET
        run: echo ${{ matrix.compiler }} | awk '/^g/ { print "TOOLSET=gcc" } /^clang/ { print "TOOLSET=clang" }' >> $GITHUB_ENV
      - name: Add repository
        run: sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
      - name: Install packages
        run: sudo apt install libgmp-dev libmpfr-dev
      - name: Checkout main boost
        run: git clone -b develop --depth 1 https://github.com/boostorg/boost.git ../boost-root
      - name: Update tools/boostdep
        run: git submodule update --init tools/boostdep
        working-directory: ../boost-root
      - name: Copy files
        run: cp -r $GITHUB_WORKSPACE/* libs/math
        working-directory: ../boost-root
      - name: Install deps
        run: python tools/boostdep/depinst/depinst.py math
        working-directory: ../boost-root
      - name: Bootstrap
        run: ./bootstrap.sh
        working-directory: ../boost-root
      - name: Generate headers
        run: ./b2 headers
        working-directory: ../boost-root
      - name: Generate user config
        run: 'echo "using $TOOLSET : : ${{ matrix.compiler }} : <cxxflags>-std=${{ matrix.standard }} ;" > ~/user-config.jam'
        working-directory: ../boost-root
      - name: Config info install
        run: ../../../b2 config_info_travis_install toolset=$TOOLSET
        working-directory: ../boost-root/libs/config/test
      - name: Config info
        run: ./config_info_travis
        working-directory: ../boost-root/libs/config/test
      - name: Checkout e_float repo
        uses: actions/checkout@v2
        with:
          repository: ckormanyos/e_float-2021
          path: ../boost-root/libs/math/test/e_float
      - name: build test_boost
        run: |
          ${{ matrix.compiler }} -Wall -Wextra -m64 -O3 -std=${{ matrix.standard }} -D${{ matrix.suite }} -Ie_float/libs/e_float/src e_float/libs/e_float/src/e_float/efx/e_float_efx.cpp e_float/libs/e_float/src/e_float/e_float.cpp e_float/libs/e_float/src/e_float/e_float_base.cpp e_float/libs/e_float/src/functions/constants/constants.cpp e_float/libs/e_float/src/functions/elementary/elementary_complex.cpp e_float/libs/e_float/src/functions/elementary/elementary_hyper_g.cpp e_float/libs/e_float/src/functions/elementary/elementary_math.cpp e_float/libs/e_float/src/functions/elementary/elementary_trans.cpp e_float/libs/e_float/src/functions/elementary/elementary_trig.cpp e_float/libs/e_float/test_boost/test_boost.cpp e_float/libs/e_float/test_boost/test_boost_real_concept.cpp e_float/libs/e_float/test_boost/test_boost_sf.cpp -o e_float_boost_test.exe
          ls -la e_float_boost_test.exe
        working-directory: ../boost-root/libs/math/test
